import { BackupRepository } from "./backup.repository.js";
import { AuditTrailRepository } from "../audit/audit.repository.js";
import { ENV } from "../../config/env.js";
import { exec } from "child_process";
import { promisify } from "util";
import path from "path";
import fs from "fs";
import crypto from "crypto";
import zlib from "zlib";
import { pipeline } from "stream/promises";

const execAsync = promisify(exec);

//Centralized config from ENV
const BACKUP_DIR = path.resolve(ENV.BACKUP_DIR);
const DB_HOST = ENV.DB_HOST;
const DB_USER = ENV.DB_USER;
const DB_PASS = ENV.DB_PASSWORD;
const DB_NAME = ENV.DB_NAME;
const MYSQLDUMP_PATH = ENV.MYSQLDUMP_PATH;
const MYSQL_PATH = ENV.MYSQL_PATH;

export class BackupService {

        //Create full database backup (FR7, UC13)
    static async createBackup(userId: number) {
        if (!fs.existsSync(BACKUP_DIR)) {
            fs.mkdirSync(BACKUP_DIR, { recursive: true });
        }

        const timestamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
        const time = new Date().toTimeString().slice(0, 8).replace(/:/g, "");
        
        // We need a temporary SQL file, and the final ENC file
        const sqlFileName = `BRMS_FULL_${timestamp}_${time}.sql`;
        const encFileName = `BRMS_FULL_${timestamp}_${time}.enc`;
        const sqlFilePath = path.join(BACKUP_DIR, sqlFileName);
        const encFilePath = path.join(BACKUP_DIR, encFileName);

        const backupId = await BackupRepository.create({
            fileName: encFileName, // Save the encrypted filename
            filePath: BACKUP_DIR,
            backupStatus: "Pending",
            backupType: "Backup"
        });

        try {
            // 1. Generate standard SQL Dump
            const passFlag = DB_PASS ? `-p${DB_PASS}` : "";
            const cmd = `"${MYSQLDUMP_PATH}" -h ${DB_HOST} -u ${DB_USER} ${passFlag} ${DB_NAME} > "${sqlFilePath}"`;
            await execAsync(cmd);

            if (!fs.existsSync(sqlFilePath)) {
                throw new Error("Backup file was not created!");
            }

            // 2. Compress and Encrypt the file
            const key = Buffer.from(ENV.BACKUP_ENCRYPTION_KEY, 'utf-8');
            const iv = Buffer.from(ENV.BACKUP_ENCRYPTION_IV, 'utf-8');
            
            await pipeline(
                fs.createReadStream(sqlFilePath),
                zlib.createGzip(),
                crypto.createCipheriv('aes-256-cbc', key, iv),
                fs.createWriteStream(encFilePath)
            );

            // 3. Delete the plain-text SQL file
            fs.unlinkSync(sqlFilePath);

            await BackupRepository.updateStatus(backupId, "Successful");
            await AuditTrailRepository.log({
                userId,
                action: "CREATE_BACKUP",
                newValue: JSON.stringify({ backupId, fileName: encFileName, filePath: BACKUP_DIR })
            });

            return { backupId, fileName: encFileName, filePath: BACKUP_DIR };

        } catch (error: any) {
            await BackupRepository.updateStatus(backupId, "Failed");
            await AuditTrailRepository.log({
                userId,
                action: "BACKUP_FAILED",
                newValue: JSON.stringify({ backupId, error: error.message })
            });
            throw { status: 500, message: `Backup failed: ${error.message}` };
        }
    }

    //Validate .sql backup file content for compatibility
    private static validateBackupContent(filePath: string): void {
        let content: string;
        try {
            //Read the first 2KB to check for dump markers
            const fd = fs.openSync(filePath, "r");
            const buffer = Buffer.alloc(2048);
            const bytesRead = fs.readSync(fd, buffer, 0, 2048, 0);
            fs.closeSync(fd);
            content = buffer.toString("utf8", 0, bytesRead);
        } catch {
            throw { status: 400, message: "Unable to read the backup file. The file may be corrupted or inaccessible." };
        }

        if (!content || content.trim().length === 0) {
            throw { status: 400, message: "The backup file is empty. Please select a valid backup file." };
        }

        //Check for MySQL dump markers
        const hasMysqlDumpMarker =
            content.includes("MySQL dump") ||
            content.includes("mysqldump") ||
            content.includes("MariaDB dump") ||
            content.includes("-- Server version") ||
            content.includes("GTID");

        if (!hasMysqlDumpMarker) {
            throw {
                status: 400,
                message: "Invalid backup file. This file does not appear to be a valid MySQL database backup. Please select a .sql file generated by this system.",
            };
        }

        //Check if the dump references the expected database name
        const hasDbReference =
            content.includes(DB_NAME) ||
            content.includes("CREATE DATABASE") ||
            content.includes("USE `");

        if (!hasDbReference) {
            throw {
                status: 400,
                message: `Incompatible backup file. This backup does not appear to be from this system (expected database: ${DB_NAME}). Please select a compatible backup file.`,
            };
        }
    }

        //Restore database from uploaded .enc file (FR7, UC13)
    static async restoreBackup(uploadedFilePath: string, originalFileName: string, userId: number) {
        if (!fs.existsSync(uploadedFilePath)) {
            throw { status: 400, message: "Backup file not found on the server!" };
        }

        const backupId = await BackupRepository.create({
            fileName: originalFileName,
            filePath: uploadedFilePath,
            backupStatus: "Pending",
            backupType: "Restore"
        });

        const tempSqlPath = `${uploadedFilePath}.temp.sql`;

        try {
            // 1. Decrypt and Decompress the uploaded file to a temporary SQL file
            const key = Buffer.from(ENV.BACKUP_ENCRYPTION_KEY, 'utf-8');
            const iv = Buffer.from(ENV.BACKUP_ENCRYPTION_IV, 'utf-8');

            try {
                await pipeline(
                    fs.createReadStream(uploadedFilePath),
                    crypto.createDecipheriv('aes-256-cbc', key, iv),
                    zlib.createGunzip(),
                    fs.createWriteStream(tempSqlPath)
                );
            } catch (err) {
                throw new Error("Failed to decrypt backup. Invalid file or wrong encryption key.");
            }

            // 2. Validate the decrypted SQL content
            this.validateBackupContent(tempSqlPath);

            // 3. Import the decrypted SQL file
            const passFlag = DB_PASS ? `-p${DB_PASS}` : "";
            const cmd = `"${MYSQL_PATH}" -h ${DB_HOST} -u ${DB_USER} ${passFlag} ${DB_NAME} < "${tempSqlPath}"`;
            await execAsync(cmd);

            // 4. Clean up the temporary plain-text SQL file
            fs.unlinkSync(tempSqlPath);

            await BackupRepository.updateStatus(backupId, "Successful");
            await AuditTrailRepository.log({
                userId,
                action: "RESTORE_BACKUP",
                newValue: JSON.stringify({ backupId, fileName: originalFileName })
            });

            return { backupId, message: "Database restored successfully!" };

        } catch (error: any) {
            // Ensure temp file is deleted even if restore fails
            if (fs.existsSync(tempSqlPath)) {
                fs.unlinkSync(tempSqlPath);
            }

            await BackupRepository.updateStatus(backupId, "Failed");
            await AuditTrailRepository.log({
                userId,
                action: "RESTORE_FAILED",
                newValue: JSON.stringify({ backupId, error: error.message })
            });

            throw { status: 500, message: `Restore failed: ${error.message}` };
        }
    }

    //Get all backup/restore logs
    static async getBackupLogs() {
        return BackupRepository.getAll();
    }

    //Download backup file
    static async getBackupFile(backupId: number) {
        const backup = await BackupRepository.getById(backupId);
        if (!backup) {
            throw { status: 404, message: "Backup record not found!" };
        }

        const fullPath = path.join(backup.FilePath, backup.FileName);
        if (!fs.existsSync(fullPath)) {
            throw { status: 404, message: "Backup file no longer exists on disk!" };
        }

        return { fullPath, fileName: backup.FileName };
    }
}